<a href="https://colab.research.google.com/github/wagber/Nootebook_Treinando_Python_1/blob/main/Exerc%C3%ADcio_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1 - Lista: Crie uma estrutura de repetição para fazer a leitura de 5 números inteiros e os armazene dentro de uma lista. Após a leitura, crie outra estrutura de repetição para somar todos os valores digitados.

In [128]:
#Forma 1

#Criando uma lista vazia
lista = []
#Criando uma estrutura de repetição para inserir valores dentro de uma lista
for i in range(5):
  numero = int(input(f'Digite o {i + 1}º número: '))
  lista.append(numero)
print(lista)

Digite o 1º número: 1
Digite o 2º número: 2
Digite o 3º número: 3
Digite o 4º número: 4
Digite o 5º número: 5
[1, 2, 3, 4, 5]


In [129]:
#Forma 2

#Ou podemos fazer o mesmo for acima dessa forma:
#Criando uma lista vazia
lista2 = []
#Criando uma estrutura de repetição para inserir valores dentro de uma lista
for i in range(1, 6):
  numero = int(input(f'Digite o {i}º número: '))
  lista2.append(numero)
print(lista2)

Digite o 1º número: 9
Digite o 2º número: 8
Digite o 3º número: 7
Digite o 4º número: 6
Digite o 5º número: 5
[9, 8, 7, 6, 5]


In [40]:
#Forma 1

print(f'Os valores da lista são {lista}')
soma = 0
#Criando estrutura de repetição para somar todos os valores de uma lista
for numeros in lista:
  soma += numeros  
print(f'A soma da lista é = {soma}')

Os valores da lista são [1, 2, 3, 4, 5]
A soma da lista é = 15


In [134]:
#Forma 2

#Ou podemos fazer a soma dos números com o for sendo feito assim:
print(f'Os valores da lista são {lista2}')
soma2 = 0
#Criando estrutura de repetição usando o tamanho da lista com a função len para somar todos os valores de uma lista
for numeros in range(len(lista2)):
  soma2 += lista2[numeros]  
print(f'A soma da lista é = {soma2}')

Os valores da lista são [9, 8, 7, 6, 5]
A soma da lista é = 35


In [133]:
'''
Também podemos converter a lista para um ARRAY e assim termos acesso a algumas funções matemáticas.
Com isso podemos usar alguns recursos como soma, média, valor mínimo, valor máximo. 
Primeiro vamos importar a biblioteca Numpy
'''
import numpy as np
#agora vamos converter a lista para um array e usar a função SUM de soma.
soma3 = np.array(lista).sum()
print(soma3)
#O mesmo serve pra Forma 2
#soma4 = np.array(lista2).sum()
#print(soma4)

15


In [135]:
#OBS. se fizermos lista.sum() teremos um erro uma vez que o atributo sum não existe para uma lista. Este tipo de atributo é exclusivo para um array.
lista2.sum()
#AttributeError: 'list' object has no attribute 'sum'

AttributeError: ignored

2 - Dicionário: Crie um dicionário para armazenar o nome e a nota de 3 alunos, fazendo a leitura dos valores por meio de uma estrutura de repetição. Depois, crie uma nova estrutura de repetição para somar todas as notas e retornar a média.

In [43]:
#Nessa estrutura a lógica usada foi: Para cada 3 loops de i 1 loop para j
boletim_notas = {}
for i in range(3):
  nome = input(f'Digite o nome do {i + 1}º aluno ')
  for j in range(1):
    nota = float(input(f'Digite a nota do {i + 1}º aluno '))
  boletim_notas[nome] = nota
print(boletim_notas)

Digite o nome do 1º aluno Wagner
Digite a nota do 1º aluno 5.9
Digite o nome do 2º aluno Fatima
Digite a nota do 2º aluno 7.1
Digite o nome do 3º aluno Aldenor
Digite a nota do 3º aluno 8.8
{'Wagner': 5.9, 'Fatima': 7.1, 'Aldenor': 8.8}


In [138]:
#Contudo temos uma forma bem mais simples e objetiva
alunos = {}
for _ in range(1, 4):
  nome = input('Digite o nome de um aluno ')
  nota = float(input('Digite a nota de um aluno '))
  alunos[nome] = nota
print(alunos)

Digite o nome de um aluno Wagner
Digite a nota de um aluno 10
Digite o nome de um aluno Bernardo
Digite a nota de um aluno 10
Digite o nome de um aluno Rodrigues
Digite a nota de um aluno 10
{'Wagner': 10.0, 'Bernardo': 10.0, 'Rodrigues': 10.0}


In [45]:
#Apresentando o dicionário criado
print(f'O dicionário boletim_notas é {boletim_notas}.')
#Mostrando o tamanho do dicionário
tamanho_dicionario = (len(boletim_notas))
print(f'Seu tamanho é de {tamanho_dicionario} posições.')
#Fazendo a soma e a média dos valores contidos no dicionário por meio de uma estrutura de repetição FOR
soma = 0
for i in boletim_notas.values():
  soma = float(soma + i)
media = round(float(soma / tamanho_dicionario),2)
#Imprimindo o valor da soma e da média
print(f'A soma das notas é igual a {soma} e a sua média é igual {media}')

O dicionário boletim_notas é {'Wagner': 5.9, 'Fatima': 7.1, 'Aldenor': 8.8}.
Seu tamanho é de 3 posições.
A soma das notas é igual a 21.8 e a sua média é igual 7.27


3 - Matriz: Dada a matriz abaixo, construa uma estrutura de repetição para percorrer e somar todos os elementos da matriz

matriz = np.array([[3, 4, 1],
                   [3, 1, 5]])

In [46]:
#Primeiramente, quando vamos trabalhar com Array temos que importar a biblioteca Numpy
import numpy as np

In [49]:
#Criando uma matriz conforme solicitada na questão:
matriz = np.array([[3,4,1],[3,1,5]])
print(matriz)

[[3 4 1]
 [3 1 5]]


In [139]:
#Primeiramente, quando vamos trabalhar com Array temos que importar a biblioteca Numpy
import numpy as np

#Criando uma matriz conforme solicitada na questão:
matriz = np.array([[3,4,1],[3,1,5]])
print(f'A matriz criada é: ')
print(matriz)
print('------------------------------------')

#Criando uma estrutura de repetição para percorrer e somar todos os alementos da matriz
soma_matriz = 0
for i in range(matriz.shape[0]):
  print(matriz[i])
  print(' ')
  for j in range(matriz.shape[1]):
    print(matriz[i][j])
    print('----')
    print(' ')
    soma_matriz += matriz[i][j]
print(f'A soma de todos os valores da matriz é igual a {soma_matriz}')

A matriz criada é: 
[[3 4 1]
 [3 1 5]]
------------------------------------
[3 4 1]
 
3
----
 
4
----
 
1
----
 
[3 1 5]
 
3
----
 
1
----
 
5
----
 
A soma de todos os valores da matriz é igual a 17
