<a href="https://colab.research.google.com/github/wagber/Nootebook_Treinando_Python_1/blob/main/Matrizes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Matrizes**

In [3]:
#Para trabalharmos com matrizes temos que importar a biblioteca Numpy que trabalha com processamentos ciêntificos e funções estatísticas
#para uso de inteligência artificial
import numpy as np

In [4]:
#Criando um arrya que é mais eficiente e mais rápido que as estruturas de lista
#Definindo linhas e colunas
matriz = np.array([[1, 2, 3],[4, 5, 6]])
#Cada [colchete] determina o número de linhas e cada elementos contido
#dentro dos [colchetes] determinam a quantidade de colunas como no exemplo acima
print(matriz)
#Observer que a matriz aqui tem duas linhas e três colunas
#[[1,2,3] linhas na horizontal
# [4,5,6]] colunas na vertical

[[1 2 3]
 [4 5 6]]


In [5]:
#Visualizando o formato da matriz usando o comando shape
matriz.shape
#Aqui ele diz a quantidade de linhas (primeiro termo) e a quantidade de colunas (segundo termo)

(2, 3)

In [6]:
#Tampbém podemos acessar a posição de uma matriz pelas LINHAS
matriz[0]

array([1, 2, 3])

In [7]:
matriz[1]

array([4, 5, 6])

In [8]:
#não é possível acessar uma posição que não existe
matriz[2]
# o índice 2 está fora dos limites do eixo 0 com tamanho 2

IndexError: ignored

In [9]:
#Tampbém podemos acessar a posição de uma matriz pelas COLUNAS, para isso usamos dois colchetes
matriz[0][0]

1

In [10]:
matriz[0][1]

2

In [11]:
matriz[0][2]

3

In [12]:
matriz[1][0]

4

In [13]:
matriz[1][1]

5

In [14]:
matriz[1][2]

6

In [15]:
#Para percorrer todos os elementos de uma matriz, para fazermos um calculo por ex.
#Nesse exemplo vamos percorrer apenas as linhas, por isso o valor da posição em
#matriz.shape[] é 0
for i in range(matriz.shape[0]):
  print(matriz[i])
#Percorrendo agora as colunas usando um for aninhado
  for j in range(matriz.shape[1]):
    print(matriz[i][j])

[1 2 3]
1
2
3
[4 5 6]
4
5
6


In [22]:
matriz2 = np.array([[2, 5 ,4],[6, 8, 9]])
print(matriz2)


[[2 5 4]
 [6 8 9]]


In [27]:
matriz3 = matriz + matriz2
print(matriz3)

[[ 3  7  7]
 [10 13 15]]


In [28]:
matriz3 = matriz - matriz2
print(matriz3)

[[-1 -3 -1]
 [-2 -3 -3]]


In [29]:
matriz3 = matriz * matriz2
print(matriz3)

[[ 2 10 12]
 [24 40 54]]


In [30]:
matriz3 = matriz ** matriz2
print(matriz3)

[[       1       32       81]
 [    4096   390625 10077696]]


In [31]:
matriz3 = matriz / matriz2
print(matriz3)

[[0.5        0.4        0.75      ]
 [0.66666667 0.625      0.66666667]]
